<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PdfEditor.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfEditor.Contracts\PdfEditor.Contracts.csproj" />
    <ProjectReference Include="..\PdfEditor.Domain\PdfEditor.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="NLog" Version="6.0.0" />
  </ItemGroup>
</Project>
